version: '3'

services:
    phppdo:
        container_name: phppdo
        image: fernando82/apache_php:72
        restart: always
        ports:
            - "80:8080"
            - "443:4433"
        volumes:
            - .:/home/app
            - ./sites-enabled/php-com-pdo.conf:/etc/apache2/sites-enabled/php-com-pdo.conf
        links:
            - mysql
        networks:
            - code-network

    mysql:
        container_name: mysql
        image: mysql:5.7.22
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data/:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=phppdo
            - MYSQL_USER=root
            - MYSQL_PASSWORD=123456
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - code-network

networks:
    code-network:
        driver: bridge